# ~/.config/starship.toml
add_newline = false

# Connected segments with chevron separators
format = """
$directory$git_branch$cmd_duration
$character"""

# Directory segment (red/pink with chevron)
[directory]
format = "[ $path ](bg:red fg:black)[](bg:yellow fg:red)"

# Git branch segment (yellow with chevron)
[git_branch]
format = "[ $symbol$branch ](bg:blue fg:white)[](bg:blue fg:yellow)"
symbol = " "

[cmd_duration]
disabled = true

# Prompt character
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

